name: Check Code Formatting

on:
  push:
    branches: "**"
  pull_request:
    types: [opened, reopened, synchronize]
    branches: [ main, dev ]

jobs:
  frontend:
    name: Check React Code Formatting
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install frontend dependencies
        working-directory: frontend
        run: npm ci

      - name: Check formatting with Prettier
        working-directory: frontend
        run: npm run prettier

      - name: Run ESLint
        working-directory: frontend
        run: npm run lint