export const carMakes = [
  'Acura',
  'Audi',
  'BMW',
  'Buick',
  'Cadillac',
  'Chevrolet',
  'Chrysler',
  'Dodge',
  'Ford',
  'GMC',
  'Honda',
  'Hyundai',
  'Infiniti',
  'Jeep',
  'Kia',
  'Lexus',
  'Lincoln',
  'Mazda',
  'Mercedes-Benz',
  'Mitsubishi',
  'Nissan',
  'Ram',
  'Subaru',
  'Tesla',
  'Toyota',
  'Volkswagen',
  'Volvo',
];

export const carModels = {
  Acura: ['ILX', 'TLX', 'RDX', 'MDX', 'NSX'],
  Audi: ['A3', 'A4', 'A6', 'A8', 'Q3', 'Q5', 'Q7', 'Q8', 'e-tron'],
  BMW: ['2 Series', '3 Series', '4 Series', '5 Series', '7 Series', 'X1', 'X3', 'X5', 'X7', 'i4', 'iX'],
  Buick: ['Encore', 'Envision', 'Enclave'],
  Cadillac: ['CT4', 'CT5', 'XT4', 'XT5', 'XT6', 'Escalade'],
  Chevrolet: [
    'Spark',
    'Malibu',
    'Camaro',
    'Corvette',
    'Trax',
    'Equinox',
    'Traverse',
    'Tahoe',
    'Suburban',
    'Silverado',
    'Colorado',
  ],
  Chrysler: ['300', 'Pacifica'],
  Dodge: ['Charger', 'Challenger', 'Durango'],
  Ford: [
    'Fiesta',
    'Focus',
    'Fusion',
    'Mustang',
    'EcoSport',
    'Escape',
    'Explorer',
    'Expedition',
    'F-150',
    'Ranger',
    'Bronco',
  ],
  GMC: ['Terrain', 'Acadia', 'Yukon', 'Sierra', 'Canyon'],
  Honda: ['Civic', 'Accord', 'Insight', 'CR-V', 'Pilot', 'Passport', 'Odyssey', 'Ridgeline'],
  Hyundai: ['Accent', 'Elantra', 'Sonata', 'Venue', 'Kona', 'Tucson', 'Santa Fe', 'Palisade'],
  Infiniti: ['Q50', 'Q60', 'QX50', 'QX60', 'QX80'],
  Jeep: ['Renegade', 'Compass', 'Cherokee', 'Grand Cherokee', 'Wrangler', 'Gladiator'],
  Kia: ['Rio', 'Forte', 'K5', 'Stinger', 'Soul', 'Seltos', 'Sportage', 'Sorento', 'Telluride'],
  Lexus: ['IS', 'ES', 'LS', 'UX', 'NX', 'RX', 'GX', 'LX'],
  Lincoln: ['Corsair', 'Nautilus', 'Aviator', 'Navigator'],
  Mazda: ['Mazda3', 'Mazda6', 'CX-3', 'CX-30', 'CX-5', 'CX-9', 'MX-5 Miata'],
  'Mercedes-Benz': ['A-Class', 'C-Class', 'E-Class', 'S-Class', 'GLA', 'GLB', 'GLC', 'GLE', 'GLS'],
  Mitsubishi: ['Mirage', 'Eclipse Cross', 'Outlander', 'Outlander Sport'],
  Nissan: [
    'Versa',
    'Sentra',
    'Altima',
    'Maxima',
    'Kicks',
    'Rogue',
    'Murano',
    'Pathfinder',
    'Armada',
    'Frontier',
    'Titan',
  ],
  Ram: ['1500', '2500', '3500', 'ProMaster'],
  Subaru: ['Impreza', 'Legacy', 'Crosstrek', 'Forester', 'Outback', 'Ascent'],
  Tesla: ['Model 3', 'Model S', 'Model X', 'Model Y'],
  Toyota: [
    'Corolla',
    'Camry',
    'Avalon',
    'Prius',
    'C-HR',
    'RAV4',
    'Highlander',
    'Sequoia',
    'Tacoma',
    'Tundra',
    '4Runner',
  ],
  Volkswagen: ['Jetta', 'Passat', 'Arteon', 'Tiguan', 'Atlas', 'ID.4'],
  Volvo: ['S60', 'S90', 'XC40', 'XC60', 'XC90'],
};

export const commonTrims = [
  'Base',
  'S',
  'SE',
  'SEL',
  'SL',
  'SV',
  'SR',
  'ST',
  'SXT',
  'L',
  'LE',
  'LX',
  'LT',
  'LTZ',
  'Limited',
  'Luxury',
  'EX',
  'EX-L',
  'Sport',
  'Touring',
  'Premium',
  'Platinum',
  'XL',
  'XLE',
  'XLT',
  'Denali',
  'R/T',
  'SRT',
  'GT',
  'Turbo',
];
